"""Data-trained RBF propeller surrogate.

``PropellerSurrogate`` reads a CSV of propeller performance
(``data/propeller_data_rbf.csv``: power, altitude, airspeed, rpm, pitch, efficiency) and fits
radial-basis-function maps for (a) the pitch governor — the pitch needed to hold a target
rpm — and (b) the efficiency. This is the *data-driven* propeller model (needs pandas); for
the analytic Hamilton-Standard model see :mod:`.propeller_hamilton`.
"""

import sys
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import Rbf
import pickle

# ==========================================
# 1. FAST SURROGATE MODEL
# ==========================================
class PropellerSurrogate:
    def __init__(self, csv_filename):
        if not os.path.exists(csv_filename):
            raise FileNotFoundError(f"CRITICAL: Data file not found at {csv_filename}")

        print(f"Loading surrogate data from: {csv_filename} ...")
        df = pd.read_csv(csv_filename)

        # EXTRACT DATA
        p = df['EM_Power_kW'].values
        a = df['Altitude_m'].values
        v = df['Airspeed_m_s'].values
        r = df['RPM'].values
        b = df['Pitch'].values          
        e = df['Efficiency'].values

        # AUTO-DETECT UNITS. Was included for safety but it can be removed if the CSV is always generated by the same script with the same units.
        if np.mean(p) > 10000:
            print("⚠️ DETECTED WATTS IN CSV. Converting to kW...")
            p = p / 1000.0
        
        if np.max(a) < 100: 
            print("⚠️ DETECTED ALTITUDE IN kft? Converting to meters...")
            a = a * 304.8

        # NORMALIZATION PARAMETERS
        self.params = {
            'p_min': p.min(), 'p_max': p.max(),
            'a_min': a.min(), 'a_max': a.max(),
            'v_min': v.min(), 'v_max': v.max(),
            'r_min': r.min(), 'r_max': r.max(),
            'b_min': b.min(), 'b_max': b.max()
        }

        print("-" * 40)
        print(f"CSV DATA RANGE (Converted):")
        print(f"Power: {self.params['p_min']:.0f} - {self.params['p_max']:.0f} kW")
        print(f"Speed: {self.params['v_min']:.0f} - {self.params['v_max']:.0f} m/s")
        print("-" * 40)

        # Normalize Data: p=power, a=altitude, v=speed, r=RPM, b=pitch
        p_n = self._norm(p, 'p')
        a_n = self._norm(a, 'a')
        v_n = self._norm(v, 'v')
        r_n = self._norm(r, 'r')
        b_n = self._norm(b, 'b')

        # Train Models
        print("Training Pitch Solver (Governor)...")
        self.pitch_model = Rbf(p_n, a_n, v_n, r_n, b_n, function='multiquadric', smooth=0.1)

        print("Training Efficiency Model...")
        self.eff_model = Rbf(p_n, a_n, v_n, b_n, r_n, e, function='multiquadric', smooth=0.1)
        print("Surrogate models ready.\n")

    def _norm(self, val, key):
        denom = self.params[f'{key}_max'] - self.params[f'{key}_min']
        if denom == 0: return 0.0 
        norm = (val - self.params[f'{key}_min']) / denom
        return np.clip(norm, 0.0, 1.0) 

    # PITCH GOVERNOR LOGIC: As inputs user gives Power, Altitude, Speed, and a target RPM.
    # It learns to predict the exact blade Pitch required to maintain that RPM.
    def solve_pitch(self, power_kw, alt_m, speed_ms, target_rpm):
        p_n = self._norm(power_kw, 'p')
        a_n = self._norm(alt_m, 'a')
        v_n = self._norm(speed_ms, 'v')
        r_n = self._norm(target_rpm, 'r')

        b_n_pred = self.pitch_model(p_n, a_n, v_n, r_n)
        pitch_deg = b_n_pred * (self.params['b_max'] - self.params['b_min']) + self.params['b_min']
        return float(pitch_deg)

    # Function that predicts efficiency given all inputs.
    # This is used to create the efficiency map and to evaluate the performance at the end.
    def get_efficiency(self, power_kw, alt_m, speed_ms, pitch_deg, rpm):
        p_n = self._norm(power_kw, 'p')
        a_n = self._norm(alt_m, 'a')
        v_n = self._norm(speed_ms, 'v')
        b_n = self._norm(pitch_deg, 'b')
        r_n = self._norm(rpm, 'r')

        eff = self.eff_model(p_n, a_n, v_n, b_n, r_n)
        return float(np.clip(eff, 0.01, 0.99)) 

    # SAVE / LOAD METHODS
    def save_model(self, filename="prop_model.pkl"):
        """Saves the trained RBF model to disk."""
        with open(filename, 'wb') as f:
            pickle.dump(self, f)
        print(f"Model saved to {filename}")

    @staticmethod
    def load_model(filename="prop_model.pkl"):
        """Loads a pre-trained model instantly."""
        with open(filename, 'rb') as f:
            print(f"Loading model from {filename}...")
            return pickle.load(f)

# ==========================================
# 2. MAIN EXECUTION
# ==========================================
def main():
    filename = r"C:\Phlygreen\propeller_data_rbf.csv"
    
    try:
        surrogate = PropellerSurrogate(filename)
    except Exception as e:
        print(f"Error: {e}")
        return

    # INPUTS 
    altitude       = 9000.0   
    tas_speed      = 140.0    
    em_power_watts = 2000000.0 
    
    gearbox_eff    = 0.98 
    prop_diameter  = 3.93 
    
    prop_power_kw = (em_power_watts * gearbox_eff) / 1000.0
    
    # Use standard cruise RPM
    target_rpm = 1000.0

    print(f"--- Simulation Inputs ---")
    print(f"Prop Power:  {prop_power_kw:.1f} kW")
    print(f"Target RPM:  {target_rpm} RPM")

    # ========================================================
    # 1. SOLVE
    # ========================================================
    required_pitch = surrogate.solve_pitch(prop_power_kw, altitude, tas_speed, target_rpm)
    efficiency = surrogate.get_efficiency(prop_power_kw, altitude, tas_speed, required_pitch, target_rpm)

    # Physics Parameters for the result printout
    n_rps = target_rpm / 60.0
    J = tas_speed / (n_rps * prop_diameter)

    print("\n" + "="*60)
    print("          RESULT")
    print("="*60)
    print(f"{'Required Pitch':<35} | {required_pitch:.2f}°")
    print(f"{'Efficiency':<35} | {efficiency:.4f}")
    
    # --- CHANGED: THRUST REPLACED WITH RPM ---
    print(f"{'RPM':<35} | {target_rpm:.1f} RPM")
    
    print(f"{'Advance Ratio (J)':<35} | {J:.3f}")
    print("="*60 + "\n")

    # ========================================================
    # 2. PLOT
    # ========================================================
    n_points = 50
    # Use detected limits for axes
    v_max_plot = min(surrogate.params['v_max'], 250)
    p_max_plot = min(surrogate.params['p_max'], prop_power_kw * 2.0)

    velocities = np.linspace(10, v_max_plot, n_points)
    powers_kw  = np.linspace(50, p_max_plot, n_points)

    J_mesh = np.zeros((n_points, n_points))
    P_mesh = np.zeros((n_points, n_points))
    Eta_mesh = np.zeros((n_points, n_points))
    
    diam_ft = prop_diameter * 3.28084
    v_tip_fts = target_rpm * diam_ft * np.pi / 60.0

    for i, vel in enumerate(velocities):
        for j, p_kw in enumerate(powers_kw):
            vel_fts = vel * 3.28084
            J_val = np.pi * vel_fts / v_tip_fts
            
            # Use the calculated pitch for the map
            eff_val = surrogate.get_efficiency(p_kw, altitude, vel, required_pitch, target_rpm)
            
            J_mesh[j, i] = J_val
            P_mesh[j, i] = p_kw      
            Eta_mesh[j, i] = eff_val

    plt.figure(figsize=(10, 7))
    cp_plot = plt.contourf(J_mesh, P_mesh, Eta_mesh, levels=20, cmap='viridis')
    plt.colorbar(cp_plot, label='Efficiency')
    
    plt.scatter(J, prop_power_kw, color='red', s=150, edgecolors='white', linewidth=2, zorder=10, label='Op Point')

    plt.title(f'Efficiency Map (Fixed Pitch: {required_pitch:.1f}°)')
    plt.xlabel('Advance Ratio (J)')
    plt.ylabel('Shaft Power (kW)')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

if __name__ == "__main__":
    main()